name: 'Packages Changed'
description: 'Find which packages have been changed, use the output to decide what jobs to run next'
author: 'Connery Noble'
inputs:
  from:
    required: false
    description: 'check for changes since previous state'
    default: 'HEAD^1'
  to:
    required: false
    description: 'check for changes to new state'
    default: 'HEAD'
  path:
    required: false
    description: 'start directory to check for changes'
outputs:
  pkgs:
    description: 'list of packages that have changed'
runs:
  using: 'node12'
  main: 'dist/index.js'
